#!/usr/bin/env python3
"""CSV to TXF converter with multiple format variations for TurboTax.

Reads a CSV file (as generated by pdf2txf.py --format csv) and produces
TXF files in several format variations. Test each with TurboTax to find
which one imports correctly.

Usage:
  python3 csv2txf.py solium.csv

This generates:
  solium_A.txf  — Format A: proceeds first, cost basis second
  solium_B.txf  — Format B: cost basis first, proceeds second
  solium_C.txf  — Format C: cost basis, proceeds, wash sale ($0.00)
  solium_D.txf  — Format D: same as C but using classic Schedule D codes
"""

import argparse
import csv
import os
import sys
from dataclasses import dataclass
from typing import Optional


@dataclass
class Trade:
    description: str
    date_acquired: str
    date_sold: str
    proceeds: float
    cost_basis: float
    wash_sale: float
    box: str  # A, B, D, E


BOX_TO_NEW_CODE = {
    "A": 711,  # Short-term, covered
    "B": 713,  # Short-term, noncovered
    "D": 715,  # Long-term, covered
    "E": 717,  # Long-term, noncovered
}

BOX_TO_CLASSIC_CODE = {
    "A": 321,  # Schedule D short-term
    "B": 321,
    "D": 323,  # Schedule D long-term
    "E": 323,
}

EOL = "\r\n"


def read_csv(filepath: str) -> list[Trade]:
    """Read trades from a CSV file."""
    trades = []
    with open(filepath, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            trades.append(Trade(
                description=row.get("Description", ""),
                date_acquired=row.get("Date Acquired", ""),
                date_sold=row.get("Date Sold", ""),
                proceeds=float(row.get("Sales Proceeds", 0)),
                cost_basis=float(row.get("Cost Basis", 0)),
                wash_sale=float(row.get("Wash Sale Loss", 0)),
                box=row.get("8949 Box", "E"),
            ))
    return trades


def write_file(filepath: str, lines: list[str]) -> None:
    """Write lines to file with CRLF endings."""
    with open(filepath, "wb") as f:
        for line in lines:
            f.write(line.encode("ascii"))
            f.write(b"\r\n")


def header_lines() -> list[str]:
    """TXF header lines."""
    from datetime import datetime
    return [
        "V042",
        "Apdf2txf",
        f"D{datetime.now().strftime('%m/%d/%Y')}",
        "^",
    ]


def format_a(trades: list[Trade]) -> list[str]:
    """Format A: 8949 codes, proceeds first then cost basis."""
    lines = header_lines()
    for t in trades:
        code = BOX_TO_NEW_CODE.get(t.box, 717)
        lines.extend([
            "TD",
            f"N{code}",
            "C1",
            "L1",
            f"P{t.description}",
            f"D{t.date_acquired}",
            f"D{t.date_sold}",
            f"${t.proceeds:.2f}",
            f"${t.cost_basis:.2f}",
            "^",
        ])
    return lines


def format_b(trades: list[Trade]) -> list[str]:
    """Format B: 8949 codes, cost basis first then proceeds."""
    lines = header_lines()
    for t in trades:
        code = BOX_TO_NEW_CODE.get(t.box, 717)
        lines.extend([
            "TD",
            f"N{code}",
            "C1",
            "L1",
            f"P{t.description}",
            f"D{t.date_acquired}",
            f"D{t.date_sold}",
            f"${t.cost_basis:.2f}",
            f"${t.proceeds:.2f}",
            "^",
        ])
    return lines


def format_c(trades: list[Trade]) -> list[str]:
    """Format C: 8949 codes, cost basis, proceeds, wash sale (3 $ lines)."""
    lines = header_lines()
    for t in trades:
        code = BOX_TO_NEW_CODE.get(t.box, 717)
        lines.extend([
            "TD",
            f"N{code}",
            "C1",
            "L1",
            f"P{t.description}",
            f"D{t.date_acquired}",
            f"D{t.date_sold}",
            f"${t.cost_basis:.2f}",
            f"${t.proceeds:.2f}",
            f"${t.wash_sale:.2f}",
            "^",
        ])
    return lines


def format_d(trades: list[Trade]) -> list[str]:
    """Format D: classic Schedule D codes (321/323), cost basis then proceeds."""
    lines = header_lines()
    for t in trades:
        code = BOX_TO_CLASSIC_CODE.get(t.box, 323)
        lines.extend([
            "TD",
            f"N{code}",
            "C1",
            "L1",
            f"P{t.description}",
            f"D{t.date_acquired}",
            f"D{t.date_sold}",
            f"${t.cost_basis:.2f}",
            f"${t.proceeds:.2f}",
            "^",
        ])
    return lines


FORMATS = {
    "A": ("proceeds first, cost basis second (8949 codes)", format_a),
    "B": ("cost basis first, proceeds second (8949 codes)", format_b),
    "C": ("cost basis, proceeds, wash sale — 3 $ lines (8949 codes)", format_c),
    "D": ("cost basis, proceeds — classic Schedule D codes (321/323)", format_d),
}


def main():
    parser = argparse.ArgumentParser(
        description="Convert CSV to TXF with multiple format variations for TurboTax testing"
    )
    parser.add_argument("input", help="Input CSV file (from pdf2txf.py --format csv)")
    parser.add_argument("--only", choices=list(FORMATS.keys()),
                        help="Generate only one format (A, B, C, or D)")
    args = parser.parse_args()

    try:
        trades = read_csv(args.input)
    except FileNotFoundError:
        print(f"Error: File not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    if not trades:
        print("Error: No trades found in CSV", file=sys.stderr)
        sys.exit(1)

    base = os.path.splitext(args.input)[0]

    formats_to_run = {args.only: FORMATS[args.only]} if args.only else FORMATS

    print(f"Read {len(trades)} trades from {args.input}")
    print()

    for key, (desc, func) in formats_to_run.items():
        outpath = f"{base}_{key}.txf"
        lines = func(trades)
        write_file(outpath, lines)
        print(f"  {outpath}  — Format {key}: {desc}")

    print()
    print("Import each file into TurboTax (File > Import > From TXF File)")
    print("to find which format works. Delete imported transactions between tests.")


if __name__ == "__main__":
    main()
